baseurl = "https://storageset.github.io/storageset2/"
title = "STORAGESET"
author = "Sabir ABIDI"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "Docs"
disableKinds = ["taxonomy","taxonomyTerm"]
pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "STORAGESET"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
